### ISSUE TITLE
Not working with `.twig` (symfony) files or `.blade` (laravel)

### ISSUE THREAD

**Issue by kanlukasz** [Janne252/vscode-fontawesome-auto-complete#11]
Not working with `.twig` (symfony) files or `.blade` (laravel)
Many people use this frameworks to create web applications

**Comment by Janne252** [comment]
Have you tried adding `**/*.twig` to the extension setting `fontAwesomeAutocomplete.patterns`? That setting defaults to
```
[ "**/*.html"  ]
```

**Comment by kanlukasz** [comment]
Ok, you got me 😜
Of course it works
