### ISSUE TITLE
Updating to 5.13 and support duotone

### ISSUE THREAD

**Issue by 50l3r** [Janne252/vscode-fontawesome-auto-complete#13]
Hi,

First of all, thank you for this extension. Looks so great!

I use Font awesome pro version and updated to latest version 5.13. It would be great that extension supports the latest version and duotone pack.

Thanks 4 all

**Comment by Janne252** [comment]
I don't think I can directly support the pro version as I currently have embedded some data files from the font awesome release files in the extension itself: https://github.com/Janne252/vscode-fontawesome-auto-complete/tree/master/data/fontawesome-5/metadata

The web download atleast contains the metadata folder: https://fontawesome.com/download
I assume the pro version has the metadata available as well.

I think there are 2 options: 
- Either get Font Awesome's approval to include pro version metadata in the extension and add a setting to the extention to enable / disable pro icons
- Or add a setting for configuring a custom metadata directory on the user's machine

**Comment by 50l3r** [comment]
Yes, I had not fallen for it. I'll try to find out an alternative

**Comment by Janne252** [comment]
Version `1.0.0` With Font Awesome Free 5.13.0 icons is now available on the marketplace.

Support for pro / duotones icons will be resolved later. I've emailed the font awesome support asking if the pro icons could be included in this extension. If that won't work, support for a local version of font awesome is likely the only option. The plus side of the latter is also being able to lock the extension to a specific version.

**Comment by 50l3r** [comment]
Great much thanks. I'l wait for more information.

Updated to 1.0 :)

**Comment by Janne252** [comment]
@50l3r No reply as of yet. I think I will implement support for local version of Font Awesome. I assume the pro version download "for web" comes with a metadata directory that matches [/data/fontawesome-5/metadata](https://github.com/Janne252/vscode-fontawesome-auto-complete/tree/master/data/fontawesome-5/metadata) except `config.json`.

**Comment by 50l3r** [comment]
Hi @Janne252, thanks 4 your time

Maybe a API proxy that shows the specific icon? I could work with you and make a hosted lambda function to show the pro icon.

**Comment by Janne252** [comment]
I would like to keep the extension offline capable. I've personally used it under varying network conditions. In the meantime I'll try contacting the support again.
