### ISSUE TITLE
Does not remove the trigger characters in *.cshtml files

### ISSUE THREAD

**Issue by SimonePaolo** [Janne252/vscode-fontawesome-auto-complete#19]
Dear Janne, thank you for the extension.

VSCode Version: 1.52.1
Font Awesome Auto-complete & Preview Version: 1.1.1

The extension does not remove the trigger characters in *.cshtml files. It works fine with *.html files.
It does not remove "fa-" from "fa-fas":
<i class="fa-fas fa-star"></i>

I have only this setting:
    "fontAwesomeAutocomplete.patterns": [
    "**/*.cshtml", "**/*.html"]

I'm making something wrong?

**Comment by Janne252** [comment]
Thanks for the report. It appears the default pattern for disabling the removal of trigger word `**/*.html` also incorrectly matches `.cshtml` files. The dot (`.`) in the pattern was never escaped. This is now fixed.

Version 1.1.2 is now available on all platforms.

**Comment by SimonePaolo** [comment]
It works!
Thank you very much for the fast update.
