### ISSUE TITLE
vue - Expected comma

### ISSUE THREAD

**Issue by Tealk** [Janne252/vscode-fontawesome-auto-complete#20]
I can't add vue in the settings unfortunately

![CleanShot 2021-02-09 at 15 58 18](https://user-images.githubusercontent.com/12276250/107381996-b0bf7f00-6aef-11eb-8e68-f2ad65d91373.jpg)

**Comment by Janne252** [comment]
Hey, have you checked the syntax of your entire configuration file? Based on the screenshot it seems that the error is caused by something above line 118.

**Comment by Tealk** [comment]
```
  "fontAwesomeAutocomplete.disableTriggerWordAutoClearPatterns": [
    "**/*.html",
    "**/*.php",
    "**/*.vue": "<font-awesome-icon :icon=\"['{style}', '{name}']\" />"
  ],
```

This is the complete block. When I remove the vue part I have no more error

**Comment by Janne252** [comment]
I believe this is what you're looking for:
```js
"fontAwesomeAutocomplete.disableTriggerWordAutoClearPatterns": [
    "**/*.html",
    "**/*.php"
],
"fontAwesomeAutocomplete.insertionTemplate": {
    "**/*.vue": "<font-awesome-icon :icon=\"['{style}', '{name}']\" />"
},
```

`"fontAwesomeAutocomplete.disableTriggerWordAutoClearPatterns"` is an array. The insertion template should be configured in `"fontAwesomeAutocomplete.insertionTemplate"`, which is an object.

**Comment by Tealk** [comment]
OK thank you
