### ISSUE TITLE
no thumbnails

### ISSUE THREAD

**Issue by Tealk** [Janne252/vscode-fontawesome-auto-complete#21]
Hello,

I don't get any thumbnails as shown in the readme.

![image](https://user-images.githubusercontent.com/12276250/107733004-2a2abd80-6cfa-11eb-96c2-c88b14413610.png)

**Comment by Janne252** [comment]
Hey, I don't think those suggestions are provided by this extension. `vscode-fontawesome-auto-complete` suggestions should have the `abc` icon (suggestion type `text`). Have you tried browsing all the way to the end of the list to see if `abc` entries appear? If so, you might be dealing with a [priority issue](https://github.com/Janne252/vscode-fontawesome-auto-complete#autocompletion-suggestions-of-this-extension-appear-at-the-end-of-the-list).

**Comment by Tealk** [comment]
I have already set the priority:
`"fontAwesomeAutocomplete.enableElevatedSortPriority": true,`

I can not find any preview below
![image](https://user-images.githubusercontent.com/12276250/107746698-8dc2e400-6d16-11eb-9fdf-80d85afbf678.png)

![image](https://user-images.githubusercontent.com/12276250/107746721-97e4e280-6d16-11eb-8ccf-f3a8fb4a8c40.png)

**Comment by Janne252** [comment]
What's the current file type? Is it present in `"fontAwesomeAutocomplete.patterns"`?

**Comment by Tealk** [comment]
I have try it in html and tpl files

```
  "fontAwesomeAutocomplete.patterns": [
    "**/*.html",
    "**/*.tpl"
  ],
```

**Comment by Janne252** [comment]
`HTML` should work out of the box. Is the extension installed? Is it enabled in the workspace? 
Have you tried setting the setting `editor.snippetSuggestions` to `"bottom"`?

This seems to be related to #15

**Comment by Tealk** [comment]
Yes, the extension is installed and activated, otherwise the message here would not make sense.
the problem is not the sorting

I have just a very strange behavior, I made a video of it once:
https://anzah.cloud/index.php/s/FfK39djRot7BPif

**Comment by Tealk** [comment]
the whole configuration

```
  "editor.snippetSuggestions": "bottom",
  "fontAwesomeAutocomplete.version": "5",
  "fontAwesomeAutocomplete.patterns": ["**/*.html", "**/*.tpl"],
  "fontAwesomeAutocomplete.triggerWord": "fa-",
  "fontAwesomeAutocomplete.insertionTemplate": {
    "**/*.vue": "<font-awesome-icon :icon=\"['{style}', '{name}']\" />"
  },
  "fontAwesomeAutocomplete.enableElevatedSortPriority": true,
```

my extensions:
```
aaron-bond.better-comments
alefragnani.Bookmarks
alefragnani.project-manager
bmewburn.vscode-intelephense-client
christian-kohler.path-intellisense
codezombiech.gitignore
CoenraadS.bracket-pair-colorizer
devonray.snippet
DotJoshJohnson.xml
eamodio.gitlens
ecmel.vscode-html-css
EditorConfig.EditorConfig
eg2.vscode-npm-script
esbenp.prettier-vscode
firefox-devtools.vscode-firefox-debug
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
foxundermoon.shell-format
Fr43nk.seito-openfile
glenn2223.live-sass
Janne252.fontawesome-autocomplete
jianbingfang.dupchecker
josee9988.minifyall
karunamurti.haml
medzhidov.font-awesome-codes-css
mrmlnc.vscode-autoprefixer
mrmlnc.vscode-scss
ms-vscode.powershell
ms-vsliveshare.vsliveshare
msjsdiag.debugger-for-chrome
nosecoolie.htmltosass
octref.vetur
pranaygp.vscode-css-peek
rifi2k.format-html-in-php
ritwickdey.LiveServer
shd101wyy.markdown-preview-enhanced
syler.sass-indented
Syler.vscode-haml-formatter
truman.autocomplate-shell
vscode-icons-team.vscode-icons
webben.browserslist
yzhang.markdown-all-in-one
Zignd.html-css-class-completion
```

**Comment by Janne252** [comment]
I installed all of those extensions via workspace config in VS Code Insiders build. I added the latest version of bootstrap's unminified css to the workspace root in order to get some css class name autocompletion. The issue did not reproduce; The thumbnail completion items were consistently appearing at the top of the list.

`test.code-workspace`
```json
{
    "folders": [
        {
            "path": "."
        }
    ],
    "settings": {},
    "extensions": {
        "recommendations": [
            "aaron-bond.better-comments",
            "alefragnani.Bookmarks",
            "alefragnani.project-manager",
            "bmewburn.vscode-intelephense-client",
            "christian-kohler.path-intellisense",
            "codezombiech.gitignore",
            "CoenraadS.bracket-pair-colorizer",
            "devonray.snippet",
            "DotJoshJohnson.xml",
            "eamodio.gitlens",
            "ecmel.vscode-html-css",
            "EditorConfig.EditorConfig",
            "eg2.vscode-npm-script",
            "esbenp.prettier-vscode",
            "firefox-devtools.vscode-firefox-debug",
            "formulahendry.auto-close-tag",
            "formulahendry.auto-rename-tag",
            "foxundermoon.shell-format",
            "Fr43nk.seito-openfile",
            "glenn2223.live-sass",
            "Janne252.fontawesome-autocomplete",
            "jianbingfang.dupchecker",
            "josee9988.minifyall",
            "karunamurti.haml",
            "medzhidov.font-awesome-codes-css",
            "mrmlnc.vscode-autoprefixer",
            "mrmlnc.vscode-scss",
            "ms-vscode.powershell",
            "ms-vsliveshare.vsliveshare",
            "msjsdiag.debugger-for-chrome",
            "nosecoolie.htmltosass",
            "octref.vetur",
            "pranaygp.vscode-css-peek",
            "rifi2k.format-html-in-php",
            "ritwickdey.LiveServer",
            "shd101wyy.markdown-preview-enhanced",
            "syler.sass-indented",
            "Syler.vscode-haml-formatter",
            "truman.autocomplate-shell",
            "vscode-icons-team.vscode-icons",
            "webben.browserslist",
            "yzhang.markdown-all-in-one",
            "Zignd.html-css-class-completion"
        ]
    }
}
```

**Comment by Tealk** [comment]
Then I do not know what I can still contribute to finding a solution, you see the behavior in the video.
If you still have ideas, I am ready to try this.

**Comment by Janne252** [comment]
All I can suggest right now is to disable some of the extensions one by one. I suspect there's a conflict or a priority issue. Could even be a performance issue where my extension takes too long to load.

**Comment by Tealk** [comment]
i have now deactivated and activated all extensions, now it seems to work
