### ISSUE TITLE
Font Awesome 6 Beta

### ISSUE THREAD

**Issue by TheRayJohnson** [Janne252/vscode-fontawesome-auto-complete#27]
Hi,

Brilliant extension! Any plans to support Font Awesome 6 (Beta)? Maybe dropping v4 and having v5 / v6 offered?

Thanks.

**Comment by Janne252** [comment]
Hey, I'm planning to support all major versions via extension settings.

**Comment by jorgesomers** [comment]
Hi @Janne252  any beta version of extension for 6 beta ?

**Comment by Janne252** [comment]
I'm going to look into adding version 6 beta during this week. The beta downloads don't seem to contain the `metadata` folder which is unfortunate.

**Comment by jorgesomers** [comment]
thanks .. !

**Comment by Janne252** [comment]
A pre-release (`.vsix`) is now available, featuring support for `v6` icons: [v1.2.0](https://github.com/Janne252/vscode-fontawesome-auto-complete/releases/tag/v1.2.0)

Some icon data is missing (changes, better search keywords, and categories) which will be added if/when a suitable source is found. It seems that Font Awesome is providing APIs for querying icons https://fontawesome.com/v6.0/docs/apis/graphql/get-started which likely will replace current `v6` metadata source.

**Comment by jorgesomers** [comment]
> A pre-release (`.vsix`) is now available, featuring support for `v6` icons: [v1.2.0](https://github.com/Janne252/vscode-fontawesome-auto-complete/releases/tag/v1.2.0)
> 
> Some icon data is missing (changes, better search keywords, and categories) which will be added if/when a suitable source is found. It seems that Font Awesome is providing APIs for querying icons https://fontawesome.com/v6.0/docs/apis/graphql/get-started which likely will replace current `v6` metadata source.

Just something I saw now .. 
This is just for VSCode, not for Visual Studio 2022 ?

**Comment by Janne252** [comment]
> > A pre-release (`.vsix`) is now available, featuring support for `v6` icons: [v1.2.0](https://github.com/Janne252/vscode-fontawesome-auto-complete/releases/tag/v1.2.0)
> > Some icon data is missing (changes, better search keywords, and categories) which will be added if/when a suitable source is found. It seems that Font Awesome is providing APIs for querying icons https://fontawesome.com/v6.0/docs/apis/graphql/get-started which likely will replace current `v6` metadata source.
> 
> Just something I saw now .. This is just for VSCode, not for Visual Studio 2022 ?

Yeah, just for VS Code.

It seems that Visual Studio has made some progress towards supporting Language Server Protocol which could possibly make it feasible to target multiple IDEs with a single LSP implementation of fontawesome-auto-complete.
