### ISSUE TITLE
Unwanted suggestions

### ISSUE THREAD

**Issue by BrightSoul** [Janne252/vscode-fontawesome-auto-complete#3]
Hi and thanks for this extension, the character preview is really helpful.
However, the extension shows its suggestions even when it shouldn't. Here's what happens when I type `span`:

![fa-suggestion](https://user-images.githubusercontent.com/1888641/46250295-f821a500-c437-11e8-88a8-1d754484f3e9.png)

Obviously the `fa-shopping-bag` and the other suggestions do not belong there. Here's my configuration, I'm using the latest version of VSCode on Windows.
```
"fontAwesomeAutocomplete.patterns": [
        "**/*.html",
        "**/*.cshtml"
    ],
"fontAwesomeAutocomplete.version": "4"
```
I think it would be best if suggestions appeared only after I typed `fa-`
Perhaps I'm missing something (?)

Thanks

**Comment by Janne252** [comment]
Hey, I've personally struggeled with the polluted list of completion items as well. I've always initiated completion of Font Awesome icons by typing `fa-` (just like your suggestion). I think this is a good solution because it also solves #2.

**Comment by Janne252** [comment]
Version 0.1.5 has now been published with the feature described above. The trigger word for auto-completing Font Awesome icons is `fa-`. This can be customized in the extension settings.

**Comment by BrightSoul** [comment]
This is seriously cool, thank you! I'd like to show this extension on a Udemy course I'm preparing, if you don't mind.

**Comment by Janne252** [comment]
Sure, I think the extension is mature enough for that.
