### ISSUE TITLE
Restrict types of suggestions (fab, far, fas)

### ISSUE THREAD

**Issue by lonix1** [Janne252/vscode-fontawesome-auto-complete#4]
Thanks for fixing #2 and #3. So now that those are out of the way, the following is the next obvious improvement. Please consider this for a future release.

I'm using the FA free tier, so I only use `fas fa-circle` for example. But the suggestions include all variations of `circle` from the `fab`, `far` and `fas` tiers.

It would be great to have a setting where I could control this, e.g. `"suggestFor": ["fab", "far", "fas"]` and I could change this to `"suggestFor": ["fas"]`.

**Comment by Janne252** [comment]
The extension is based on the icons.json file from the free pack, I don't think it's suggesting any pro icons?
![image](https://user-images.githubusercontent.com/4705573/46255215-0eb11600-c4a3-11e8-8f1b-8c27a263e467.png)

`far fa-circle` and `fas fa-circle` are both available in the free pack.

**Comment by lonix1** [comment]
You are right it's only the free pack. Thanks for explaining.
